# Force SortMergeJoin.

spark.sql.adaptive.enabled                      true
spark.sql.adaptive.coalescePartitions.enabled   true
spark.sql.adaptive.skewJoin.enabled             false

spark.sql.autoBroadcastJoinThreshold            -1
spark.sql.adaptive.autoBroadcastJoinThreshold   -1

spark.sql.join.preferSortMergeJoin              true
spark.sql.shuffledHashJoinFactor                100

spark.executor.cores                            8
spark.executor.memory                           24g
spark.executor.memoryOverhead                   4g
spark.driver.memory                             8g
spark.memory.offHeap.enabled                    true
spark.memory.offHeap.size                       8g
